hungry_hippo_app/urls.py
from django.urls import path
from . import views, api

app_name = 'hungry_hippo_app'
urlpatterns = [
    # views paths
    path("", views.entry, name="entry"),
    path("register", views.register, name="register"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("index", views.index, name='index'),
    
    # API Paths
    path("upload_images_folder", api.upload_images_folder, name="upload_images_folder"),
    path("process_batch", api.process_batch, name="process_batch"),
    path('upload_tag/<int:user_image_set>', api.upload_tag, name='upload_tag'),
    path('get_browse_images/<int:user_image_set>', api.get_browse_images, name="get_browse_images"),


    # Sandbox
    # path('update_form1', sandbox.update_form1),
    # path('update_form2', sandbox.update_form2)
    # path('analyse_imageFile_Vs_PILFile/<int:user_image_set>', sandbox.analyse_imageFile_Vs_PILFile, name='analyse_imageFile_Vs_PILFile' )
    
]

hungry_hippo_proj/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("hungry_hippo_app.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hungry_hippo_app/views.py
# Standard
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import redirect, get_object_or_404

# Authentication
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Database
from django.db import IntegrityError
from .models import *

# File Handling
from django.core.files.storage import default_storage
from django.core.exceptions import SuspiciousFileOperation
import os

# Forms
from django.views.decorators.csrf import csrf_exempt
from .forms import *

# Image Handling
from PIL import Image
from django.core.files import File
from django.core.files.images import ImageFile


# There are a lot of Django Queries here
# https://docs.djangoproject.com/en/dev/topics/db/queries/


def entry(request):
    # If user is authenticated load profile
    if request.user.is_authenticated:
        current_user = User.objects.get(pk = request.user.id)
        print(f"############# current user => {current_user}")
        user_profile = User_Profile.objects.get(user_id_fk = current_user)
        profile_id = user_profile.user_profile_id
        user_name = current_user.username
        return HttpResponseRedirect(reverse("hungry_hippo_app:index"))
    else:
        # load authentication options
        return render(request, "hungry_hippo_app/authenticate_options.html")


def register(request):
    print(f"#### register ####")      
        
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        
        #Django validation checks username is unique

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        
        if password != confirmation:    
            return render(request, "hungry_hippo_app/register.html", {
                "message": "Passwords must match."
            })
            
        # Check if email address is already in use
        email_address_is_taken = User.objects.filter(email = request.POST['email'])
        if email_address_is_taken:
                context_dictionary = {"message": "email already being used."}
                return render(request, "hungry_hippo_app/register.html", context_dictionary)
            
        # TODO Confirm and Validate Registration by email/phone

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()

        except IntegrityError:
            # remove the user profile directory area
            return render(request, "hungry_hippo_app/register.html", {
                "message": "Username already taken."
            })
            
        login(request, user)
        create_user_profile(request)
        return HttpResponseRedirect(reverse('hungry_hippo_app:index'))
    else:
        return render(request, "hungry_hippo_app/register.html")
    
    
def create_user_profile(request):
    print (f"#### create_user_profile ####")
    
    # Define filesystem directory tree for the users uploads
    # At this point The user has been entered in the User table and has been logged in
    current_user = User.objects.get(pk = request.user.id)
    username = current_user.username   
       
    # its also important to remember where you have defined MEDIA_ROOT and MEDIA_URL for user uploads
    # MEDIA_ROOT is where the app will upload files
    # MEDIA_URL is the root url realtive to the project root directory. This is where it will look for files when you give it a pathname such as a username
    media_root = settings.MEDIA_ROOT
    media_url  = settings.MEDIA_URL
    print(f"MEDIA_ROOT => {media_root}") # /home/artillery/webdev-apps/courses/CS50/Project-4/hungry_hippo_app/user_profiles
    print(f"MEDIA_URL => {media_url}")   # /user_profiles/     
       
    # Create an instance in the User_Profile table and assign defaults where necessary
    try:
        
        folder = os.path.join(media_url,username)
        print(f"user folder => {folder}")
        new_user_profile = User_Profile(user_id_fk = current_user,
                                        user_profile_folder = folder)
        new_user_profile.save()
            
    except IntegrityError:
        # delete the user profile directory area
        # delete User
        return render(request, "hungry_hippo_app/register.html", {
            "message": "Error creating User Profile.",
        })
        
    return
    

 
    
def page_404(request, message):
    pass
    

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            current_user = User.objects.get(pk = request.user.id)
            return HttpResponseRedirect(reverse("hungry_hippo_app:index"))
        else:
            return render(request, "hungry_hippo_app/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "hungry_hippo_app/login.html")


def logout_view(request):
    # Delete all the processing data associated with the user
    print(f"Deleting User Data")
    current_user = User.objects.get(pk = request.user.id)
    user_profile = User_Profile.objects.get(user_id_fk = current_user)
    
    user_image_sets = Image_Set.objects.filter(user_profile_id_fk = user_profile.pk)
    for image_set in user_image_sets:
        image_set.delete()
        
    print(f"Logging Out")
    
    logout(request)
    print(f"Redirect")
    return HttpResponseRedirect(reverse("hungry_hippo_app:entry"))


@login_required
def index(request):
    tag_form = Tag_Upload_Form()
    source_folder_form = Source_Folder_Form()
    action_set_image_widths = Action_Set_Image_Widths()
    action_set_image_heights = Action_Set_Image_Heights() 
    tag_placement = Tag_Position_Form()
    
    
    image_url = os.path.join(settings.MEDIA_URL,'hippo1.jpg')
    return render(request, "hungry_hippo_app/index.html", {
                    'debug_message': 'CropperJS Debug',
                    'work_image': image_url,
                    'tag_form': tag_form,
                    'source_folder_form': source_folder_form,
                    'action_set_image_widths': action_set_image_widths,
                    'action_set_image_heights': action_set_image_heights,  
                    'tag_placement': tag_placement                 
    })

hungry_hippo_app/templates/hungry_hippo_app/authenticate_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="shortcut icon" href="#">
        <title>{% block title %}Authentication{% endblock %}</title>
         <link href="{% static 'hungry_hippo_app/css/style.css' %}" rel="stylesheet"> 
    </head>
    <body>
        <div class='main-window-wrapper'>

            <div class = "hungry-hippo-main-flexbox">

                <div class="authenticate-main-wrapper">

                    <div class = "authenticate-logo-wrapper">
                        <img src="{% static 'hungry_hippo_app/images/logos/panda1.jpg' %}">
                    </div>
            
                    <div class = "site-enerjon">
                        <div class="hungry-hippo-app-title">Hungry Hippo</div>
                        <div class="tagline">Image Batch Processor</div>
                    </div>

                    {% block authenticate_panel %}
                    {% endblock %}
                </div>
            </div>


        </div>
    </body>
</html>

hungry_hippo_app/templates/hungry_hippo_app/authenticate_options.html
{% extends "hungry_hippo_app/authenticate_layout.html" %}
{% load static %}

{% block title %}
    hungry_hippo_app Authentication
{% endblock %}

{% block authenticate_panel %}



        <div class = "authenticate-login-wrapper">
            <a href="{% url 'hungry_hippo_app:login' %}"> 
                <div class = "login-btn authenticate-btn" id = 'login-btn'>Login</div>
            </a>
        
            <a href="{% url 'hungry_hippo_app:register' %}">
                <div class = "login-btn authenticate-btn" id = 'register-btn'>Register</div>
            </a>
        </div>


{% endblock %}

hungry_hippo_app/templates/hungry_hippo_app/browse_images_gallery.html
{% load static %}



        {% for image in images%}
            <div class="gallery-grid-item">                

                <label for = "{{image.file_id}}" class="gallery-image-label">
                    <input type="radio" class = "gallery-browser-input" id = "{{image.file_id}}" name = "images" value = "{{image.image_file.url}}" data-imagename={{image.image_file.name}}>
                    <img class="gallery-image" src="{{image.image_file.url}}">
                </label>
            </div>
        {% endfor %}

hungry_hippo_app/templates/hungry_hippo_app/debug.html
<!--
    <div class='debug-window'>
        <p id="viewsize"></p>
    
        <script>
        var w = window.innerWidth;
        var h = window.innerHeight;
        
        var x = document.getElementById("viewsize");
        x.innerHTML = "Browser width: " + w + ", height: " + h + ".";
        </script>


        <div class = "cropperjs-data crop-box">
            <div class = 'data-col'>
                <div>x-offeset: <span id='crop-box-x-offset'></span></div>
                <div>y-offset: <span id='crop-box-y-offset'></span></div>
                <div>crop width: <span id='crop-box-width'></span></div>
                <div>crop height: <span id='crop-box-height'></span></div>
                <div>crop rotation: <span id='crop-box-rotation'></span></div>
            </div>

        </div>

        <div class='debug-msg'>
            {{debug_message|safe}}
        </div>
    </div>
-->


<!--
    <div class = "cropperjs-data">
        <div class = 'data-col'>
            <div>x-offeset: <span id='crop-box-x-offset'>0</span></div>
            <div>y-offset: <span id='crop-box-y-offset'>0</span></div>
        </div>

        <div class = 'data-col'>
            <div>crop width: <span id='crop-box-width'>0</span></div>
            <div>crop height: <span id='crop-box-height'>0</span></div>
        </div>

        <div class = 'data-col'>
            <div>Slider Value: <span id = 'slider-value'>0</span></div>
            <div>crop rotation: <span id='crop-box-rotation'>0</span></div>
        </div>

        <div class = 'data-col'>
            <div>Image Tag: 
                <div id = 'tag-area'>No Tag Uploaded</div>
            </div>
        </div>    
    </div>
-->


<div class = "image-tag-data">
    <div class = 'data-col pil-image'>
        <div><b>PIL 1:</b> <span id='pil-data1'>0</span></div>
        <div><B>PIL 2:</b> <span id='pil-data2'>0</span></div>
    </div>

    <div class = 'data-col pil-image'>
        <div><b>PIL 3:</b> <span id='pil-data3'>0</span></div>
        <div><b>PIL 4:</b> <span id='pil-data4'>0</span></div>
    </div>

    <div class = 'data-col django-image'>
        <div><b>django name:</b> <div id='django-name'>0</div></div>
        <div><b>django path:</b> <div id='django-path'>0</div></div>
    </div>

    <div class = 'data-col django-image'>
        <div><b>url:</b> <div id='django-url'>0</div></div>
        <div><b>abs-path:</b> <div id='django-abs-path'>0</div></div>
    </div>


    <div class = 'data-col'>
        <div>Image Tag: 
            <div id = 'tag-area'>None</div>
        </div>
    </div>
    <div class = 'data-col'>
        <div class="tag-thumb-wrapper">
            <img src="" id="tag-thumb">
        </div>
    </div>

    
</div>

hungry_hippo_app/templates/hungry_hippo_app/login.html
{% extends "hungry_hippo_app/authenticate_layout.html" %}

{% block authenticate_panel %}

    <div class="login-page-wrapper">
        <div class="login-title">
            Login
        </div>

        <div class="login-form-wrapper">
            <form class ="login-form" action="{% url 'hungry_hippo_app:login' %}" method="post">
                {% csrf_token %}
                <input autofocus class="authentication-form-input" type="text" name="username" placeholder="Username">
                <input class="authentication-form-input" type="password" name="password" placeholder="Password">
                <input class = "login-btn" type="submit" value="Login">
            </form>
            {% if message %}
            <div class="login-message">{{ message }}</div>
        {% endif %}
        </div>

        <div class="authenticate-redirect">
            <div>Don't have an account?</div>
            <div> <a href="{% url 'hungry_hippo_app:register' %}">Register here.</a></div>
        </div>

    </div>

{% endblock %}

hungry_hippo_app/templates/hungry_hippo_app/main_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="#">
    <title>
        {% block title %}
        {% endblock %}
    </title>

        <link href="{% static 'hungry_hippo_app/css/style.css' %}" rel="stylesheet">
        <link  href="{% static 'hungry_hippo_app/javascript/cropperjs/node_modules/cropperjs/dist/cropper.min.css' %}" rel="stylesheet">

</head>
<body>


    <div class='main-window-wrapper'>
            {% block hungry_hippo %}
            {% endblock %}
    </div>

</body>
</html>

{% block script %} 

{% endblock %}

hungry_hippo_app/templates/hungry_hippo_app/register.html
{% extends "hungry_hippo_app/authenticate_layout.html" %}

{% block authenticate_panel %}

    <div class="login-page-wrapper">
        <div class="login-title">
            Register
        </div>



        <div class="register-form-wrapper">
            <form class='regsier-form' action="{% url 'hungry_hippo_app:register' %}" method="post">
                {% csrf_token %}
                <input class="authentication-form-input" autofocus type="text" name="username" placeholder="Username">
                <input class="authentication-form-input" type="email" name="email" placeholder="Email Address">
                <input class="authentication-form-input" type="password" name="password" placeholder="Password">
                <input class="authentication-form-input" type="password" name="confirmation" placeholder="Confirm Password">
                <input class = "login-btn" type="submit" value="Register">
            </form>

            {% if message %}
                <div class="login-message">{{ message }}</div>
            {% endif %}
        </div>

        <div class="authenticate-redirect">
            <div>Already have an account?</div>
            <div> <a href="{% url 'hungry_hippo_app:login' %}">Log In here.</a></div>
        </div>
    </div>

{% endblock %}

hungry_hippo_app/templates/hungry_hippo_app/zip_download_link.html
{%load static %}

<a href="{{zip_download_path }}" download>
    <div class='zip-download-btn' id = 'zipfile-btn'>
            Download
    </div>
</a>